---
- name: Load OS-specific variables
  ansible.builtin.include_vars: "{{ role_path }}/vars/{{ ansible_distribution }}.yml"
  tags: ansible-role-strongswan

- name: Run configuration validation tasks
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"
  tags: ansible-role-strongswan

- name: Run stroke tasks
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/stroke.yml"
  when: strongswan_mode == "stroke"
  tags: ansible-role-strongswan

- name: Run vici tasks
  ansible.builtin.include_tasks: "{{ role_path }}/tasks/vici.yml"
  when: strongswan_mode == "vici"
  tags: ansible-role-strongswan
