---
- name: Install the Strongswan packages (vici)
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ strongswan_vici_packages + strongswan_additional_packages }}"
  notify: Restart Strongswan (vici)
  tags: ansible-role-strongswan
