---
- name: Install the Strongswan packages (vici)
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ strongswan_vici_packages + strongswan_additional_packages }}"
  notify: Restart Strongswan (vici)
  tags: ansible-role-strongswan

- name: Write swanctl.conf
  ansible.builtin.template:
    src: "{{ role_path }}/templates/swanctl.conf.j2"
    dest: "{{ strongswan_base_path }}/swanctl/swanctl.conf"
    owner: root
    group: root
    mode: "0644"
    lstrip_blocks: true
  notify: Restart Strongswan (vici)
  tags: ansible-role-strongswan

- name: Write strongswan.conf
  ansible.builtin.template:
    src: "{{ role_path }}/templates/strongswan.conf.j2"
    dest: "{{ strongswan_base_path }}/strongswan.conf"
    owner: root
    group: root
    mode: "0644"
    lstrip_blocks: true
  notify: Restart Strongswan (vici)
  tags: ansible-role-strongswan
