---
- name: Disable stroke mode when using vici
  tags: ansible-role-strongswan
  block:
    - name: Stop and disable strongswan-starter service (stroke)
      ansible.builtin.service:
        name: "{{ strongswan_stroke_service_name }}"
        state: stopped
        enabled: false
      failed_when: false

    - name: Remove stroke configuration files
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "{{ strongswan_base_path }}/ipsec.conf"
        - "{{ strongswan_base_path }}/ipsec.secrets"
      failed_when: false

    - name: Remove stroke packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: absent
      loop: "{{ strongswan_stroke_packages }}"
      failed_when: false

- name: Install the Strongswan packages (vici)
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ strongswan_vici_packages + strongswan_both_packages + strongswan_additional_packages }}"
  notify: Restart Strongswan (vici)
  tags: ansible-role-strongswan

- name: Write swanctl.conf
  ansible.builtin.template:
    src: "{{ role_path }}/templates/swanctl.conf.j2"
    dest: "{{ strongswan_base_path }}/swanctl/swanctl.conf"
    owner: root
    group: root
    mode: "0600"
    lstrip_blocks: true
  notify: Restart Strongswan (vici)
  tags: ansible-role-strongswan

- name: Write strongswan.conf
  ansible.builtin.template:
    src: "{{ role_path }}/templates/strongswan.conf.j2"
    dest: "{{ strongswan_base_path }}/strongswan.conf"
    owner: root
    group: root
    mode: "0644"
    lstrip_blocks: true
  notify: Restart Strongswan (vici)
  tags: ansible-role-strongswan
