---
- name: Converge
  hosts: all
  become: true
  gather_facts: true
  vars:
    ipsec_conf: |

    ipsec_secrets: |

  tasks:
    - name: Run the ansible-role-strongswan role
      ansible.builtin.include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
