---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Install required networking tools
      ansible.builtin.package:
        name:
          - iputils-ping
          - net-tools
          - iproute2
          - bridge-utils
        state: present
      when: ansible_os_family == 'Debian'
      ignore_errors: true

    - name: Enable IP forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: true

    - name: Create TUN interface tun0 for peer1
      ansible.builtin.shell: |
        ip tuntap add name tun0 mode tun
        ip addr add 192.168.1.1/24 dev tun0
        ip link set tun0 up
      when: inventory_hostname in groups['peer1']
      ignore_errors: true

    - name: Create TUN interface tun0 for peer2
      ansible.builtin.shell: |
        ip tuntap add name tun0 mode tun
        ip addr add 192.168.2.1/24 dev tun0
        ip link set tun0 up
      when: inventory_hostname in groups['peer2']
      ignore_errors: true
