---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true
  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Install required networking tools
      ansible.builtin.package:
        name:
          - iputils-ping
          - net-tools
          - iproute2
          - bridge-utils
        state: present
      when: ansible_os_family == 'Debian'
      ignore_errors: true

    - name: Enable IP forwarding
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: true

    - name: Create dummy interface for peer1 tunnel subnet
      ansible.builtin.command: ip link add dummy0 type dummy
      when: inventory_hostname in groups['peer1']
      ignore_errors: true
      
    - name: Configure peer1 tunnel gateway IP
      ansible.builtin.command: ip addr add 192.168.1.1/24 dev dummy0
      when: inventory_hostname in groups['peer1']
      ignore_errors: true

    - name: Create dummy interface for peer2 tunnel subnet
      ansible.builtin.command: ip link add dummy0 type dummy
      when: inventory_hostname in groups['peer2']
      ignore_errors: true
      
    - name: Configure peer2 tunnel gateway IP
      ansible.builtin.command: ip addr add 192.168.2.1/24 dev dummy0
      when: inventory_hostname in groups['peer2']
      ignore_errors: true
      
    - name: Bring up dummy interfaces
      ansible.builtin.command: ip link set dummy0 up
      ignore_errors: true
