# SPDX-FileCopyrightText: 2025 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later
---
- name: Prepare StrongSwan Molecule tests
  hosts: all
  become: true
  gather_facts: true
  pre_tasks:
    - name: Ensure apt cache is updated for StrongSwan Molecule tests preparation
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false

    - name: Ensure ping utility is installed for StrongSwan Molecule tests preparation
      ansible.builtin.package:
        name: iputils-ping
        state: present
      when: ansible_os_family == 'Debian'

    - name: Ensure IP forwarding is enabled for StrongSwan Molecule tests preparation
      ansible.posix.sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: true

    - name: Add tunnel IP to loopback for peer1 # noqa: no-changed-when
      ansible.builtin.command: ip addr add 192.168.1.1/32 dev lo
      when: inventory_hostname in groups['peer1']

    - name: Add tunnel IP to loopback for peer2 # noqa: no-changed-when
      ansible.builtin.command: ip addr add 192.168.2.1/32 dev lo
      when: inventory_hostname in groups['peer2']
